# Generated by Django 5.2.17 on 2026-09-30 22:29

import apps.common.money
import django.core.validators
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models


def ensure_whole_rial_prices(apps, schema_editor):
    product = apps.get_model("products", "Product")
    for product_id, price in product.objects.values_list("pk", "price").iterator():
        if price != price.to_integral_value():
            raise RuntimeError(
                f"Product {product_id} has a fractional IRR price; "
                "correct it before applying this migration."
            )


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.RunPython(
            ensure_whole_rial_prices,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price', django.db.models.functions.math.Floor('price'))), name='products_product_price_whole_irr'),
        ),
    ]
