# Generated by Django 5.2.17 on 2026-09-30 16:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CONSUMED', 'Consumed'), ('RELEASED', 'Released')], default='ACTIVE', max_length=8)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_reservations', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_reservations', to='products.product')),
            ],
            options={
                'indexes': [models.Index(condition=models.Q(('status', 'ACTIVE')), fields=['product', 'expires_at'], name='orders_active_reservation_idx')],
                'constraints': [models.UniqueConstraint(fields=('order', 'product'), name='orders_unique_reservation_per_product'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='orders_reservation_quantity_gt_zero'), models.CheckConstraint(condition=models.Q(('status__in', ('ACTIVE', 'CONSUMED', 'RELEASED'))), name='orders_reservation_valid_status'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='orders_reservation_expiry_after_creation')],
            },
        ),
    ]
