# Generated by Django 5.2.17 on 2026-09-30

import decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_inventoryreservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="discount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=24,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0.00"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="grand_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=24,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0.00"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_total",
            field=models.DecimalField(
                decimal_places=2,
                default=decimal.Decimal("0.00"),
                max_digits=24,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0.00"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=24,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0.00"))
                ],
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="line_total",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=22,
                validators=[
                    django.core.validators.MinValueValidator(decimal.Decimal("0.00"))
                ],
            ),
        ),
    ]
