# Generated by Django 5.2.17 on 2026-09-30 22:29

import apps.common.money
import django.core.validators
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models


def ensure_whole_rial_order_amounts(apps, schema_editor):
    order = apps.get_model("orders", "Order")
    order_fields = (
        "subtotal",
        "discount_total",
        "shipping_total",
        "grand_total",
    )
    for values in order.objects.values_list("pk", *order_fields).iterator():
        order_id, *amounts = values
        if any(amount != amount.to_integral_value() for amount in amounts):
            raise RuntimeError(
                f"Order {order_id} has a fractional IRR amount; "
                "correct it before applying this migration."
            )

    order_item = apps.get_model("orders", "OrderItem")
    for item_id, unit_price, line_total in order_item.objects.values_list(
        "pk",
        "unit_price",
        "line_total",
    ).iterator():
        if (
            unit_price != unit_price.to_integral_value()
            or line_total != line_total.to_integral_value()
        ):
            raise RuntimeError(
                f"Order item {item_id} has a fractional IRR amount; "
                "correct it before applying this migration."
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address'),
        ('orders', '0003_expand_order_total_precision'),
        ('products', '0004_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.RunPython(
            ensure_whole_rial_order_amounts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal', django.db.models.functions.math.Floor('subtotal'))), name='orders_order_subtotal_whole_irr'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('discount_total', django.db.models.functions.math.Floor('discount_total'))), name='orders_order_discount_whole_irr'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('shipping_total', django.db.models.functions.math.Floor('shipping_total'))), name='orders_order_shipping_whole_irr'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('grand_total', django.db.models.functions.math.Floor('grand_total'))), name='orders_order_grand_whole_irr'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price', django.db.models.functions.math.Floor('unit_price'))), name='orders_item_unit_price_whole_irr'),
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total', django.db.models.functions.math.Floor('line_total'))), name='orders_item_line_total_whole_irr'),
        ),
    ]
