# Generated by Django 5.2.17 on 2026-09-30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carts", "0002_cart_customer_cascade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveBigIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
