# Generated by Django 5.2.17 on 2026-09-30 19:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_expand_order_total_precision'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('gateway', models.CharField(max_length=50)),
                ('gateway_reference', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_attempts', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['order', 'created_at'], name='payments_order_created_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'PENDING')), fields=('order',), name='payments_one_pending_order'), models.UniqueConstraint(fields=('gateway', 'gateway_reference'), name='payments_gateway_ref_unique'), models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'SUCCESS', 'FAILED'))), name='payments_attempt_valid_status'), models.CheckConstraint(condition=models.Q(('amount__gte', 0)), name='payments_attempt_amount_gte_0'), models.CheckConstraint(condition=models.Q(('currency', 'USD')), name='payments_attempt_currency_usd'), models.CheckConstraint(condition=models.Q(('gateway', ''), _negated=True), name='payments_attempt_gateway_set'), models.CheckConstraint(condition=models.Q(('gateway_reference', ''), _negated=True), name='payments_attempt_ref_set')],
            },
        ),
    ]
