# Generated by Django 5.2.17 on 2026-09-30 19:33

import uuid
from django.db import migrations, models


def populate_idempotency_keys(apps, schema_editor):
    payment_attempt = apps.get_model("payments", "PaymentAttempt")
    for attempt_id in payment_attempt.objects.values_list("pk", flat=True).iterator():
        payment_attempt.objects.filter(pk=attempt_id).update(
            idempotency_key=uuid.uuid4()
        )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_expand_order_total_precision'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='payments_attempt_ref_set',
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='idempotency_key',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_idempotency_keys,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='idempotency_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='payment_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='gateway_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('gateway_reference__isnull', True), models.Q(('gateway_reference', ''), _negated=True), _connector='OR'), name='payments_attempt_ref_set'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('payment_url__isnull', True), models.Q(('payment_url', ''), _negated=True), _connector='OR'), name='payments_attempt_url_set'),
        ),
    ]
