# Generated by Django 5.2.17 on 2026-09-30 22:29

import apps.common.money
import django.core.validators
import django.db.models.functions.math
from decimal import Decimal
from django.db import migrations, models


def migrate_payment_currency_to_irr(apps, schema_editor):
    payment_attempt = apps.get_model("payments", "PaymentAttempt")
    payment_attempt.objects.update(currency="IRR")


def migrate_payment_currency_to_usd(apps, schema_editor):
    payment_attempt = apps.get_model("payments", "PaymentAttempt")
    payment_attempt.objects.update(currency="USD")


def ensure_whole_rial_payment_amounts(apps, schema_editor):
    payment_attempt = apps.get_model("payments", "PaymentAttempt")
    for attempt_id, amount in payment_attempt.objects.values_list(
        "pk",
        "amount",
    ).iterator():
        if amount != amount.to_integral_value():
            raise RuntimeError(
                f"Payment attempt {attempt_id} has a fractional IRR amount; "
                "correct it before applying this migration."
            )


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_discount_total_alter_order_grand_total_and_more'),
        ('payments', '0002_remove_paymentattempt_payments_attempt_ref_set_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentattempt',
            name='payments_attempt_currency_usd',
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=24, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), apps.common.money.validate_whole_rial]),
        ),
        migrations.AlterField(
            model_name='paymentattempt',
            name='currency',
            field=models.CharField(default='IRR', max_length=3),
        ),
        migrations.RunPython(
            migrate_payment_currency_to_irr,
            migrate_payment_currency_to_usd,
        ),
        migrations.RunPython(
            ensure_whole_rial_payment_amounts,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('amount', django.db.models.functions.math.Floor('amount'))), name='payments_attempt_amount_whole_irr'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'IRR')), name='payments_attempt_currency_irr'),
        ),
    ]
