# Generated by Django 5.2.17 on 2026-09-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_discount_total_alter_order_grand_total_and_more'),
        ('payments', '0003_remove_paymentattempt_payments_attempt_currency_usd_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaleWebhookUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True)),
                ('event_type', models.CharField(choices=[('PRE_CHECKOUT', 'Pre-checkout'), ('SUCCESSFUL_PAYMENT', 'Successful payment')], max_length=18)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('gateway', 'provider_transaction_id'), name='payments_gateway_tx_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('provider_transaction_id__isnull', True), models.Q(('provider_transaction_id', ''), _negated=True), _connector='OR'), name='payments_attempt_tx_set'),
        ),
        migrations.AddConstraint(
            model_name='balewebhookupdate',
            constraint=models.CheckConstraint(condition=models.Q(('event_type__in', ('PRE_CHECKOUT', 'SUCCESSFUL_PAYMENT'))), name='payments_bale_update_event_valid'),
        ),
    ]
