# Generated by Django 5.2.17 on 2026-09-30 23:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def mark_existing_receipts_processed(apps, schema_editor):
    bale_webhook_update = apps.get_model("payments", "BaleWebhookUpdate")
    bale_webhook_update.objects.update(status="PROCESSED")


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_discount_total_alter_order_grand_total_and_more'),
        ('payments', '0004_balewebhookupdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balewebhookupdate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=24, null=True),
        ),
        migrations.AddField(
            model_name='balewebhookupdate',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='balewebhookupdate',
            name='payment_attempt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bale_webhook_updates', to='payments.paymentattempt'),
        ),
        migrations.AddField(
            model_name='balewebhookupdate',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='balewebhookupdate',
            name='provider_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='balewebhookupdate',
            name='received_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='balewebhookupdate',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='pre_checkout_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='balewebhookupdate',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            mark_existing_receipts_processed,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='balewebhookupdate',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('PENDING', 'PROCESSING', 'PROCESSED', 'REJECTED'))), name='payments_bale_update_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='balewebhookupdate',
            constraint=models.CheckConstraint(condition=models.Q(('provider_transaction_id__isnull', True), models.Q(('provider_transaction_id', ''), _negated=True), _connector='OR'), name='payments_bale_update_tx_set'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('gateway', 'pre_checkout_transaction_id'), name='payments_gateway_precheckout_unique'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('pre_checkout_transaction_id__isnull', True), models.Q(('pre_checkout_transaction_id', ''), _negated=True), _connector='OR'), name='payments_attempt_precheckout_set'),
        ),
    ]
